### ISSUE TITLE
Add the linear-algebra crate `static-math`

### ISSUE THREAD

**Issue by elsuizo** [robotics-rs/robotics.rs#7]
Hi i create a crate of linear algebra and transformations(rotations, translations...) with Robotics in mind:

https://crates.io/crates/static-math

 - Matrix from 2x2 to 6x6
 - Vector from 2D to 6D
 - a lot of tests
 - Safe (NO `unsafe` code in it)
 - correct treatment of floating point variables
 - correct treatment of Inverses
 - minimum dependencies

And fast you could view the performance here comparing with others crates:

https://github.com/bitshifter/mathbench-rs

**Comment by OTL** [comment]
Could you give us a PR?
